import { resolve } from 'node:path';
import type { Finding } from '../inventory/schema.js';
import { exists, readJson } from '../util/fs.js';
import { stamp, template } from './shared.js';
import type { NewFile, PortStep, Transform, TransformContext } from './types.js';

type VercelJson = {
  crons?: { path: string; schedule: string }[];
  [key: string]: unknown;
};

export type CronJob = {
  id: string;
  schedule: string;
  timezone: 'UTC';
  method: 'GET';
  url: string;
  headers: Record<string, string>;
};

function slug(input: string): string {
  return input
    .replace(/^\/+/, '')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

/** Stable, readable, collision-free ids: the route plus its position. */
export function jobsFrom(crons: { path: string; schedule: string }[]): CronJob[] {
  const seen = new Map<string, number>();
  return crons.map((cron) => {
    const base = slug(cron.path) || 'root';
    const n = (seen.get(base) ?? 0) + 1;
    seen.set(base, n);
    return {
      id: n === 1 ? base : `${base}-${n}`,
      schedule: cron.schedule,
      timezone: 'UTC',
      method: 'GET',
      url: `\${PUBLIC_BASE_URL}${cron.path}`,
      headers: {
        authorization: 'Bearer ${CRON_SECRET}',
        'user-agent': 'porter-cron/1.0',
      },
    };
  });
}

/** Host crontab: one curl line per job, pinned to UTC like Vercel's scheduler. */
export function renderCrontab(jobs: CronJob[]): string {
  const lines = [
    '# Generated by Porter (Severance agent 03).',
    '# Install with `crontab infra/porter.crontab` as the user that has PUBLIC_BASE_URL and',
    '# CRON_SECRET in its environment. CRON_TZ is honoured by cronie and Vixie cron 4.1+;',
    '# on other implementations convert the hours to your server timezone instead.',
    'CRON_TZ=UTC',
    '',
  ];
  for (const job of jobs) {
    lines.push(
      `${job.schedule} curl -fsS -m 60 -H "Authorization: Bearer $CRON_SECRET" "$PUBLIC_BASE_URL${job.url.replace('${PUBLIC_BASE_URL}', '')}" >/dev/null`,
    );
  }
  return lines.join('\n') + '\n';
}

/**
 * Coolify "Scheduled Tasks" run a command inside the app container, so the call
 * goes to localhost. Node's fetch is used because the slim image has no curl.
 */
export function renderCoolifyTasks(jobs: CronJob[]): string {
  const rows = jobs.map((job) => {
    const path = job.url.replace('${PUBLIC_BASE_URL}', '');
    const command =
      `node -e "fetch('http://127.0.0.1:3000${path}',{headers:{authorization:'Bearer '+process.env.CRON_SECRET}})` +
      `.then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"`;
    return `| ${job.id} | \`${job.schedule}\` | \`${command}\` |`;
  });
  return [
    '# Coolify scheduled tasks',
    '',
    'Generated by Porter (Severance agent 03). In Coolify, open the application, go to',
    '**Scheduled Tasks**, and add one task per row. Coolify has no import format, so this',
    'is a checklist. Frequencies are UTC cron expressions, matching the original `vercel.json`.',
    '',
    '| Name | Frequency | Command |',
    '|------|-----------|---------|',
    ...rows,
    '',
    'The commands run inside the app container, so `CRON_SECRET` must be set in the',
    "application's environment, and the container listens on port 3000.",
    '',
  ].join('\n');
}

const INSTRUMENTATION = `// Runs the cron schedule inside the Next.js server process. With several
// replicas every one of them runs this; set REDIS_URL so a per-minute lock lets
// exactly one replica fire each job.
export async function register() {
  if (process.env.NEXT_RUNTIME !== 'nodejs') return;
  const { pathToFileURL } = await import('node:url');
  const { join } = await import('node:path');
  const runner = pathToFileURL(join(process.cwd(), 'infra', 'scheduler.mjs')).href;
  const { startScheduler } = await import(/* webpackIgnore: true */ runner);
  await startScheduler({ manifestPath: join(process.cwd(), 'infra', 'porter-schedules.json') });
}
`;

export const cronTransform: Transform = {
  id: 'cron',
  kind: 'cron',
  summary: 'Move vercel.json cron declarations to a scheduler that actually calls them',

  claims(finding: Finding) {
    return finding.kind === 'cron';
  },

  async plan(findings: Finding[], ctx: TransformContext): Promise<PortStep | null> {
    const path = resolve(ctx.repoRoot, 'vercel.json');
    const json = await readJson<VercelJson>(path);
    if (!json?.crons?.length) return null;

    const jobs = jobsFrom(json.crons);
    const scheduler = ctx.target.scheduler;

    const nextJson = { ...json };
    delete nextJson.crons;

    const newFiles: NewFile[] = [
      {
        path: 'infra/porter-schedules.json',
        contents: JSON.stringify({ version: 1, scheduler, jobs }, null, 2) + '\n',
      },
    ];
    const caveats: string[] = [
      'Vercel cron expressions are UTC. The generated schedule is UTC as well; keep it that way or convert the hours on purpose.',
      'Vercel sent `Authorization: Bearer $CRON_SECRET` and the routes check it. Set the same `CRON_SECRET` ' +
        'for the app and for the scheduler.',
    ];

    if (scheduler === 'compose-sidecar' || scheduler === 'node-cron') {
      newFiles.push({
        path: 'infra/scheduler.mjs',
        contents: stamp(await template('cron/scheduler.mjs'), 'vercel.json crons (scheduler runtime)'),
      });
    }

    if (scheduler === 'compose-sidecar') {
      caveats.push(
        'Run `node infra/scheduler.mjs` as its own container next to the app (Porter adds this service to ' +
          '`docker-compose.porter.yml` when it generates one). Smoke-test any job with ' +
          '`node infra/scheduler.mjs --once <id>`.',
      );
    } else if (scheduler === 'node-cron') {
      const instrumentation = `${ctx.layout.srcRoot ? ctx.layout.srcRoot + '/' : ''}instrumentation.ts`;
      if (await exists(resolve(ctx.repoRoot, instrumentation))) {
        caveats.push(
          `${instrumentation} already exists, so it was not overwritten. Add \`startScheduler()\` from ` +
            '`infra/scheduler.mjs` to its `register()` function to run crons in-process.',
        );
      } else {
        newFiles.push({
          path: instrumentation,
          contents: stamp(INSTRUMENTATION, 'vercel.json crons (in-process scheduler)'),
          skipIfExists: true,
        });
      }
      caveats.push(
        'The in-process scheduler runs in every replica. Set `REDIS_URL` so a per-minute lock lets exactly one ' +
          'replica fire each job; without it every replica fires every job.',
        'Copy `infra/` into the runtime image: the scheduler is loaded from there at startup.',
      );
    } else if (scheduler === 'system-crontab') {
      newFiles.push({ path: 'infra/porter.crontab', contents: renderCrontab(jobs) });
    } else if (scheduler === 'coolify') {
      newFiles.push({ path: 'infra/coolify-scheduled-tasks.md', contents: renderCoolifyTasks(jobs) });
    }

    return {
      id: 'cron',
      kind: 'cron',
      title: 'Move Vercel cron jobs to a scheduler that actually calls them',
      rationale:
        '`vercel.json` cron entries are only read by Vercel. Off-platform the routes still respond but nothing ' +
        'ever calls them, and nothing errors — the digest just stops arriving. Porter extracts the schedule into ' +
        `\`infra/porter-schedules.json\` and generates the runner for a \`${scheduler}\` scheduler, so the same ` +
        'routes are called on the same UTC schedule with the same bearer token.',
      discharges: findings.map((f) => f.id),
      editedFiles: ['vercel.json'],
      fileEdits: [{ path: 'vercel.json', contents: JSON.stringify(nextJson, null, 2) + '\n' }],
      newFiles,
      deps: [],
      env: [
        {
          name: 'PUBLIC_BASE_URL',
          example: 'https://app.example.com',
          required: true,
          description: 'Absolute production origin the scheduler calls.',
        },
        {
          name: 'CRON_SECRET',
          example: 'CHANGE_ME_32_BYTES_OF_RANDOM',
          required: true,
          description: 'Bearer token sent by scheduled jobs to cron route handlers.',
        },
      ],
      caveats,
    };
  },
};
