import { resolve } from 'node:path';
import type { Finding, LockInKind } from '../inventory/schema.js';
import { findNextConfigObject, upsertProperty } from '../util/ast.js';
import { exists } from '../util/fs.js';
import { stamp } from './shared.js';
import type { NewFile, PortStep, PortTarget, Transform, TransformContext } from './types.js';

type PackageManager = 'npm' | 'pnpm' | 'yarn' | 'bun';

function installCommands(pm: PackageManager): { copy: string; install: string; build: string } {
  switch (pm) {
    case 'pnpm':
      return {
        copy: 'COPY package.json pnpm-lock.yaml* ./',
        install: 'RUN corepack enable && pnpm install --frozen-lockfile',
        build: 'RUN corepack enable && pnpm run build',
      };
    case 'yarn':
      return {
        copy: 'COPY package.json yarn.lock* ./',
        install: 'RUN corepack enable && yarn install --frozen-lockfile',
        build: 'RUN corepack enable && yarn build',
      };
    // Bun is not in the slim Node image; npm reads the same package.json.
    default:
      return {
        copy: 'COPY package.json package-lock.json* ./',
        install: 'RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi',
        build: 'RUN npm run build',
      };
  }
}

export function renderDockerfile(opts: {
  pm: PackageManager;
  hasPublic: boolean;
  cacheHandler: boolean;
  copyInfra: boolean;
}): string {
  const { copy, install, build } = installCommands(opts.pm);
  const lines = [
    'FROM node:20-bookworm-slim AS deps',
    'WORKDIR /app',
    copy,
    install,
    '',
    'FROM node:20-bookworm-slim AS build',
    'WORKDIR /app',
    'COPY --from=deps /app/node_modules ./node_modules',
    'COPY . .',
    'ENV NEXT_TELEMETRY_DISABLED=1',
    '# Pages that read Redis or S3 while `next build` prerenders them need those values at build',
    '# time. Pass them with `--build-arg`, or mark such routes `export const dynamic = "force-dynamic"`.',
    '# ARG REDIS_URL',
    build,
    '',
    'FROM node:20-bookworm-slim AS runner',
    'WORKDIR /app',
    'ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=3000 HOSTNAME=0.0.0.0',
    'RUN groupadd --system --gid 1001 nodejs && useradd --system --uid 1001 --gid nodejs nextjs',
  ];
  if (opts.hasPublic) lines.push('COPY --from=build --chown=nextjs:nodejs /app/public ./public');
  lines.push(
    'COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./',
    'COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static',
  );
  // Standalone output serialises next.config, so the handler path is resolved
  // at build time; it must exist at the same absolute path in the runtime image.
  if (opts.cacheHandler) lines.push('COPY --from=build --chown=nextjs:nodejs /app/cache-handler.cjs ./cache-handler.cjs');
  if (opts.copyInfra) lines.push('COPY --from=build --chown=nextjs:nodejs /app/infra ./infra');
  lines.push(
    'USER nextjs',
    'EXPOSE 3000',
    `HEALTHCHECK --interval=30s --timeout=5s --start-period=20s CMD node -e "fetch('http://127.0.0.1:3000/').then(r=>process.exit(r.status<500?0:1)).catch(()=>process.exit(1))"`,
    'CMD ["node", "server.js"]',
    '',
  );
  return lines.join('\n');
}

export const DOCKERIGNORE = [
  'node_modules',
  '.next',
  '.git',
  '.gitignore',
  '.porter',
  '.env',
  '.env.*',
  '!.env.example',
  'npm-debug.log*',
  'Dockerfile',
  'docker-compose*.yml',
  '',
].join('\n');

export function renderNginxConf(): string {
  return [
    '# Generated by Porter (Severance agent 03).',
    '# Balances across every `app` replica. The variable in proxy_pass makes nginx re-resolve',
    "# the service name through Docker's DNS (127.0.0.11), so replicas that come and go are found.",
    'server {',
    '  listen 80;',
    '  resolver 127.0.0.11 valid=5s ipv6=off;',
    '  set $upstream http://app:3000;',
    '',
    '  location / {',
    '    proxy_pass $upstream;',
    '    proxy_http_version 1.1;',
    '    proxy_set_header Host $host;',
    '    proxy_set_header X-Real-IP $remote_addr;',
    '    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
    '    proxy_set_header X-Forwarded-Proto $scheme;',
    '    proxy_set_header Upgrade $http_upgrade;',
    '    proxy_set_header Connection "upgrade";',
    '    client_max_body_size 25m;',
    '  }',
    '}',
    '',
  ].join('\n');
}

export function renderCompose(opts: {
  target: PortTarget;
  kinds: Set<LockInKind>;
  hasRedis: boolean;
  hasBlob: boolean;
  hasCron: boolean;
}): string {
  const { target } = opts;
  const multi = target.replicas > 1;
  const ownMinio = opts.hasBlob && target.objectStore === 'minio';

  const dependsOn: string[] = [];
  if (opts.hasRedis) dependsOn.push('      redis:\n        condition: service_healthy');
  if (ownMinio) dependsOn.push('      minio-init:\n        condition: service_completed_successfully');

  const lines: string[] = [
    '# Generated by Porter (Severance agent 03).',
    '#',
    '#   cp .env.porter.example .env.porter        # then replace every CHANGE_ME',
    '#   docker compose --env-file .env.porter -f docker-compose.porter.yml up --build',
    '#',
    '# This file is a starting point for a single host. Review it before production.',
    'services:',
    '  app:',
    '    build: .',
    '    env_file: .env.porter',
    '    restart: unless-stopped',
  ];
  if (multi) {
    lines.push(`    deploy:\n      replicas: ${target.replicas}`, '    expose:', '      - "3000"');
  } else {
    lines.push('    ports:', '      - "3000:3000"');
  }
  if (dependsOn.length) lines.push('    depends_on:', ...dependsOn);

  if (multi) {
    lines.push(
      '',
      '  proxy:',
      '    image: nginx:1.27-alpine',
      '    restart: unless-stopped',
      '    ports:',
      '      - "3000:80"',
      '    volumes:',
      '      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro',
      '    depends_on:',
      '      - app',
    );
  }

  if (opts.hasRedis) {
    lines.push(
      '',
      '  redis:',
      `    image: ${target.redis === 'valkey' ? 'valkey/valkey:8-alpine' : target.redis === 'dragonfly' ? 'docker.dragonflydb.io/dragonflydb/dragonfly' : 'redis:7-alpine'}`,
      '    restart: unless-stopped',
      // AOF so a restart does not drop rate-limit windows, sessions and the ISR cache.
      '    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:-CHANGE_ME}"]',
      '    environment:',
      '      REDIS_PASSWORD: ${REDIS_PASSWORD:-CHANGE_ME}',
      '    volumes:',
      '      - redis-data:/data',
      '    healthcheck:',
      '      test: ["CMD-SHELL", "redis-cli -a \\"$$REDIS_PASSWORD\\" ping | grep PONG"]',
      '      interval: 5s',
      '      timeout: 3s',
      '      retries: 10',
    );
  }

  if (ownMinio) {
    lines.push(
      '',
      '  minio:',
      '    image: minio/minio:latest',
      '    restart: unless-stopped',
      '    command: server /data --console-address ":9001"',
      '    environment:',
      '      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}',
      '      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}',
      '    volumes:',
      '      - minio-data:/data',
      '',
      '  minio-init:',
      '    image: minio/mc:latest',
      '    depends_on:',
      '      - minio',
      '    environment:',
      '      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}',
      '      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}',
      '      S3_BUCKET: ${S3_BUCKET}',
      '    entrypoint: >',
      '      /bin/sh -c "',
      '      until mc alias set local http://minio:9000 $$S3_ACCESS_KEY_ID $$S3_SECRET_ACCESS_KEY; do sleep 1; done;',
      '      mc mb --ignore-existing local/$$S3_BUCKET;',
      '      mc anonymous set download local/$$S3_BUCKET;',
      '      "',
    );
  }

  if (opts.hasCron && target.scheduler === 'compose-sidecar') {
    lines.push(
      '',
      '  scheduler:',
      '    image: node:20-alpine',
      '    restart: unless-stopped',
      '    working_dir: /srv',
      '    command: ["node", "scheduler.mjs"]',
      '    env_file: .env.porter',
      '    volumes:',
      '      - ./infra/scheduler.mjs:/srv/scheduler.mjs:ro',
      '      - ./infra/porter-schedules.json:/srv/porter-schedules.json:ro',
      '    depends_on:',
      '      - app',
    );
  }

  const volumes: string[] = [];
  if (opts.hasRedis) volumes.push('  redis-data:');
  if (ownMinio) volumes.push('  minio-data:');
  if (volumes.length) lines.push('', 'volumes:', ...volumes);

  return lines.join('\n') + '\n';
}

/**
 * Gives the app a way to be built and run off-platform: a multi-stage
 * Dockerfile for Next.js standalone output, and (when one is not already
 * present) a compose file wiring in only the services the other transforms made
 * necessary.
 */
export const deployTransform: Transform = {
  id: 'deploy',
  kind: 'build-output',
  summary: 'Generate a container build and a compose stack for the ported app',

  claims(finding: Finding) {
    return finding.kind === 'build-output';
  },

  async plan(findings: Finding[], ctx: TransformContext): Promise<PortStep | null> {
    if (await exists(resolve(ctx.repoRoot, 'Dockerfile'))) return null;

    const kinds = new Set<LockInKind>(ctx.inventory.findings.map((f) => f.kind));
    const hasRedis = kinds.has('kv-store') || kinds.has('isr');
    const hasBlob = kinds.has('blob-storage');
    const hasCron = kinds.has('cron');
    const pm = ctx.inventory.framework.packageManager;

    const edited = new Set<string>();
    const caveats: string[] = [];

    if (ctx.target.standalone) {
      const configPath = ctx.inventory.framework.configPath;
      const source = configPath ? ctx.project.getSourceFile(resolve(ctx.repoRoot, configPath)) : undefined;
      const config = source ? findNextConfigObject(source) : null;
      if (config && configPath) {
        if (upsertProperty(config, 'output', "'standalone'")) edited.add(configPath);
      } else if (ctx.inventory.framework.output !== 'standalone') {
        caveats.push(
          `Could not set \`output: 'standalone'\` in ${configPath ?? 'next.config'}; the generated Dockerfile expects ` +
            'it. Add it by hand.',
        );
      }
    }

    const newFiles: NewFile[] = [
      {
        path: 'Dockerfile',
        contents: stamp(
          renderDockerfile({
            pm,
            hasPublic: await exists(resolve(ctx.repoRoot, 'public')),
            cacheHandler: kinds.has('isr'),
            copyInfra: hasCron && ctx.target.scheduler === 'node-cron',
          }),
          "Vercel's platform-managed build output",
        ).replace(/^\/\/ /gm, '# '),
      },
      { path: '.dockerignore', contents: DOCKERIGNORE, skipIfExists: true },
      {
        path: 'docker-compose.porter.yml',
        contents: renderCompose({ target: ctx.target, kinds, hasRedis, hasBlob, hasCron }),
        skipIfExists: true,
      },
    ];
    if (ctx.target.replicas > 1) {
      newFiles.push({ path: 'infra/nginx.conf', contents: renderNginxConf(), skipIfExists: true });
    }

    if (await exists(resolve(ctx.repoRoot, 'pnpm-workspace.yaml'))) {
      caveats.push('This looks like a monorepo (pnpm-workspace.yaml). The Dockerfile assumes the app is at the repo root; adjust the COPY paths.');
    }
    if (pm === 'bun') {
      caveats.push('The Dockerfile installs with npm because the slim Node image has no Bun. Switch the base image if you rely on bun.lockb.');
    }
    caveats.push(
      'Pages that read Redis or S3 during `next build` prerendering need those variables at build time ' +
        '(uncomment `ARG REDIS_URL` in the Dockerfile) — or mark such routes `force-dynamic`.',
      'The compose file is a single-host starting point. Set real secrets in `.env.porter` and put TLS in ' +
        'front of it before serving traffic.',
    );
    if (ctx.target.replicas > 1) {
      caveats.push(
        `The stack runs ${ctx.target.replicas} app replicas behind nginx. State that lived in one process ` +
          '(in-memory caches, module-level counters) is now per-replica.',
      );
    }

    return {
      id: 'deploy',
      kind: 'build-output',
      title: 'Add a container build and compose stack',
      rationale:
        'Nothing in the repository said how to build or run the app anywhere but Vercel. Porter adds a ' +
        "multi-stage Dockerfile for Next.js `output: 'standalone'` (non-root, with a healthcheck) and a compose " +
        'file that wires in only what this app needs: ' +
        [hasRedis && 'Redis', hasBlob && (ctx.target.objectStore === 'minio' ? 'MinIO' : 'external object storage'), hasCron && `a ${ctx.target.scheduler} scheduler`]
          .filter(Boolean)
          .join(', ') +
        '.',
      discharges: findings.map((f) => f.id),
      editedFiles: [...edited].sort(),
      newFiles,
      deps: [],
      env: [
        ...(hasRedis
          ? [
              {
                name: 'REDIS_PASSWORD',
                example: 'CHANGE_ME',
                required: true,
                description: 'Password for the compose Redis service. Keep it identical to the one in REDIS_URL.',
              },
            ]
          : []),
      ],
      caveats,
    };
  },
};
