import { readFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ts, type SourceFile } from 'ts-morph';
import type { Finding } from '../inventory/schema.js';
import { exists, readText } from '../util/fs.js';
import type { ProjectLayout, TransformContext } from './types.js';

const here = dirname(fileURLToPath(import.meta.url));

/**
 * Templates live outside `src/` so they are never compiled — they are source
 * text Porter copies into somebody else's repo. Resolve them relative to the
 * built file, walking up out of `dist/transforms`.
 */
export async function template(relativePath: string): Promise<string> {
  const roots = [
    resolve(here, '../../templates'),
    resolve(here, '../../../templates'),
  ];
  for (const root of roots) {
    try {
      return await readFile(resolve(root, relativePath), 'utf8');
    } catch {
      continue;
    }
  }
  throw new Error(`Porter template not found: ${relativePath}`);
}

/** Marker every generated source file starts with. Used to skip our own output. */
export const GENERATED_MARKER = '// Generated by Porter';

/**
 * Prepend the provenance header every generated file carries.
 *
 * A reviewer opening an unfamiliar file in their own repo should learn, in the
 * first three lines, what wrote it and what it replaced. Generated code that
 * does not say it is generated is how codemods lose people's trust.
 */
export function stamp(contents: string, replaces: string): string {
  const header = [
    `${GENERATED_MARKER} (Severance agent 03).`,
    `// Replaces: ${replaces}`,
    '// Review this file as you would any dependency you are about to own.',
    '',
  ].join('\n');
  return header + contents;
}

/**
 * Source files of the app being ported. Excludes dependencies, build output and
 * anything Porter itself generated — a transform that re-reads its own shims
 * would "fix" them on the next pass.
 */
export function appSourceFiles(ctx: TransformContext): SourceFile[] {
  return ctx.project.getSourceFiles().filter((file) => {
    const path = file.getFilePath();
    if (path.includes('/node_modules/')) return false;
    if (path.includes('/.next/')) return false;
    if (file.getFullText().startsWith(GENERATED_MARKER)) return false;
    return true;
  });
}

/** All distinct files named by a set of findings. */
export function filesOf(findings: Finding[]): string[] {
  const set = new Set<string>();
  for (const finding of findings) {
    for (const evidence of finding.evidence) set.add(evidence.file);
  }
  return [...set].sort();
}

/** Findings of a kind whose evidence names one of the given import specifiers. */
export function findingsMatching(findings: Finding[], specifiers: string[]): Finding[] {
  return findings.filter((finding) =>
    finding.evidence.some((e) =>
      specifiers.some((s) => e.matched === s || e.matched.startsWith(s + '/')),
    ),
  );
}

// ---------------------------------------------------------------------------
// Project layout
// ---------------------------------------------------------------------------

/** Directory `@/*` points at, relative to the repo ('' or 'src'), or null if unmapped. */
function readAliasRoot(root: string): string | null {
  for (const name of ['tsconfig.json', 'jsconfig.json']) {
    const configPath = join(root, name);
    if (!ts.sys.fileExists(configPath)) continue;

    // TypeScript's own reader understands comments, trailing commas and
    // `extends`, all of which real tsconfig files use and JSON.parse rejects.
    const read = ts.readConfigFile(configPath, ts.sys.readFile);
    if (read.error) continue;
    const parsed = ts.parseJsonConfigFileContent(read.config, ts.sys, root, undefined, configPath);

    const targets = parsed.options.paths?.['@/*'];
    if (!targets || targets.length === 0) continue;

    const base = (parsed.options.pathsBasePath as string | undefined) ?? root;
    const first = targets[0]!.replace(/\/?\*$/, '');
    const relDir = relative(root, resolve(base, first)).split(sep).join('/');
    if (relDir.startsWith('..')) continue;
    return relDir;
  }
  return null;
}

export async function resolveLayout(repoRoot: string): Promise<ProjectLayout> {
  const root = resolve(repoRoot);

  const rootApp = await exists(join(root, 'app'));
  const rootPages = await exists(join(root, 'pages'));
  const srcApp = await exists(join(root, 'src', 'app'));
  const srcPages = await exists(join(root, 'src', 'pages'));

  // Next.js prefers a root `app`/`pages` over `src/` when both exist.
  const srcRoot: ProjectLayout['srcRoot'] = rootApp || rootPages ? '' : srcApp || srcPages ? 'src' : '';
  const appDir = rootApp ? 'app' : srcApp ? 'src/app' : null;

  const aliasRoot = readAliasRoot(root);
  const libBase = aliasRoot ?? srcRoot;
  const libDir = `${libBase ? libBase + '/' : ''}lib/porter`;

  // Line endings and indentation are sampled from the config, which every Next
  // repo has and which Porter is about to edit. Matching them keeps the diff to
  // the lines that actually changed.
  let sample = '';
  for (const name of ['next.config.mjs', 'next.config.js', 'next.config.ts', 'next.config.cjs', 'package.json']) {
    const text = await readText(join(root, name));
    if (text) {
      sample = text;
      break;
    }
  }
  const crlf = sample.includes('\r\n');
  const indented = sample.split(/\r?\n/).filter((line) => /^\s+\S/.test(line));
  const tabs = indented.filter((line) => line.startsWith('\t')).length;
  const fours = indented.filter((line) => /^ {4}\S/.test(line)).length;
  const twos = indented.filter((line) => /^ {2}\S/.test(line)).length;
  const indent: ProjectLayout['indent'] = tabs > twos && tabs > fours ? 'tab' : fours > twos ? 'four' : 'two';

  return { srcRoot, appDir, aliasRoot, libDir, crlf, indent };
}

/**
 * The import specifier a call site should use to reach a generated module.
 *
 * Aliased repos get `@/lib/porter/<module>`. Everyone else gets a relative path
 * computed from the importing file, which is uglier but always resolves.
 */
export function libImport(
  layout: ProjectLayout,
  repoRoot: string,
  fromFile: string,
  moduleName: string,
): string {
  if (layout.aliasRoot !== null) return `@/lib/porter/${moduleName}`;

  const target = join(repoRoot, layout.libDir, moduleName);
  let spec = relative(dirname(fromFile), target).split(sep).join('/');
  if (!spec.startsWith('.')) spec = './' + spec;
  return spec;
}

/** Convenience wrapper used by transforms, which always hold a context. */
export function importFor(ctx: TransformContext, file: SourceFile, moduleName: string): string {
  return libImport(ctx.layout, ctx.repoRoot, file.getFilePath(), moduleName);
}

/** Repo-relative path of a generated module file. */
export function libPath(layout: ProjectLayout, relativePath: string): string {
  return `${layout.libDir}/${relativePath}`;
}
