import assert from 'node:assert/strict';
import { test } from 'node:test';
import { cp, mkdtemp, readFile, rm, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { scanRepo } from '../src/inventory/scan.js';
import { portRepo } from '../src/runtime/port.js';

const FIXTURE = resolve(dirname(fileURLToPath(import.meta.url)), '../fixtures/victim-app');

async function fixtureCopy(): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), 'porter-port-'));
  const app = join(dir, 'app-under-test');
  await cp(FIXTURE, app, { recursive: true });
  return app;
}

const read = (root: string, path: string) => readFile(join(root, path), 'utf8');

test('ports the fixture, then has nothing left to do', async (t) => {
  const root = await fixtureCopy();
  t.after(() => rm(dirname(root), { recursive: true, force: true }));

  const first = await portRepo(root, { writeArtifacts: false });
  assert.ok(first.plan.steps.length >= 7, `expected the full set of steps, got ${first.plan.steps.length}`);
  assert.ok(first.diff.includes('diff --git'), 'expected a git-style diff');
  assert.equal(first.applied, true);

  // Every finding is either fixed or reported; nothing is silently dropped.
  const unhandledKinds = first.plan.unhandled.map((f) => f.kind);
  assert.deepEqual(unhandledKinds, [], `unexpected unhandled findings: ${unhandledKinds.join(', ')}`);

  // Idempotency: the second run finds nothing to do and writes nothing.
  const second = await portRepo(root, { writeArtifacts: false });
  assert.equal(second.plan.steps.length, 0, 'second run should be a no-op');
  assert.equal(second.diff, '');

  // And a fresh scan agrees the repo is clean.
  assert.deepEqual((await scanRepo(root)).findings, []);
});

test('rewrites imports to the shims it actually writes', async (t) => {
  const root = await fixtureCopy();
  t.after(() => rm(dirname(root), { recursive: true, force: true }));
  await portRepo(root, { writeArtifacts: false });

  assert.match(await read(root, 'lib/rate-limit.ts'), /from '@\/lib\/porter\/kv'/);
  assert.match(await read(root, 'lib/storage.ts'), /from '@\/lib\/porter\/storage'/);
  assert.match(await read(root, 'app/gallery/page.tsx'), /from '@\/lib\/porter\/storage\/client'/);
  // handleUpload runs on the server even though it is imported from /client.
  assert.match(await read(root, 'app/api/upload/route.ts'), /from '@\/lib\/porter\/storage\/handle-upload'/);
  assert.match(await read(root, 'middleware.ts'), /from '@\/lib\/porter\/request-context'/);

  for (const shim of [
    'lib/porter/kv/index.ts',
    'lib/porter/storage/index.ts',
    'lib/porter/storage/client.ts',
    'lib/porter/storage/handle-upload.ts',
    'lib/porter/request-context.ts',
    'lib/porter/edge-config.ts',
  ]) {
    assert.match(await read(root, shim), /^\/\/ Generated by Porter/, `${shim} should be generated and stamped`);
  }

  const pkg = JSON.parse(await read(root, 'package.json'));
  for (const gone of ['@vercel/kv', '@vercel/blob', '@vercel/analytics', '@vercel/speed-insights']) {
    assert.ok(!pkg.dependencies[gone], `${gone} should be removed`);
  }
  assert.ok(pkg.dependencies['ioredis'] && pkg.dependencies['sharp'] && pkg.dependencies['@aws-sdk/client-s3']);
});

test('keeps the revalidate contract and drops only edge pins', async (t) => {
  const root = await fixtureCopy();
  t.after(() => rm(dirname(root), { recursive: true, force: true }));
  await portRepo(root, { writeArtifacts: false });

  // Freshness settings are the app's own contract and must survive the port.
  assert.match(await read(root, 'app/page.tsx'), /export const revalidate = 3600/);
  assert.match(await read(root, 'app/products/[slug]/page.tsx'), /export const revalidate = 600/);
  // Edge pins are what actually has to go.
  assert.ok(!(await read(root, 'app/api/geo/route.ts')).includes("runtime = 'edge'"));
  assert.ok(!(await read(root, 'middleware.ts')).includes("runtime: 'edge'"));
  // The matcher next to the removed pin is untouched.
  assert.match(await read(root, 'middleware.ts'), /matcher:/);
});

test('removes analytics beacons and their markup without leaving litter', async (t) => {
  const root = await fixtureCopy();
  t.after(() => rm(dirname(root), { recursive: true, force: true }));
  await portRepo(root, { writeArtifacts: false });

  const layout = await read(root, 'app/layout.tsx');
  assert.ok(!layout.includes('@vercel/analytics'));
  assert.ok(!layout.includes('<Analytics'));
  assert.ok(!layout.includes('{null}'), 'should delete the elements, not replace them with {null}');
  assert.match(layout, /\{children\}/);
});

test('a dry run reports the real diff and changes nothing on disk', async (t) => {
  const root = await fixtureCopy();
  t.after(() => rm(dirname(root), { recursive: true, force: true }));

  const before = await read(root, 'lib/rate-limit.ts');
  const dry = await portRepo(root, { dryRun: true });

  assert.equal(dry.applied, false);
  assert.ok(dry.diff.includes('diff --git'), 'a dry run should still produce a diff');
  assert.ok(dry.touched.includes('package.json'));
  assert.equal(dry.plan.repoRoot, resolve(root), 'the plan should describe the real repo');
  assert.equal(await read(root, 'lib/rate-limit.ts'), before, 'dry run must not write');

  await assert.rejects(() => read(root, 'lib/porter/kv/index.ts'));
});

test('moves crons out of vercel.json into a schedule the runner understands', async (t) => {
  const root = await fixtureCopy();
  t.after(() => rm(dirname(root), { recursive: true, force: true }));
  await portRepo(root, { writeArtifacts: false });

  const vercelJson = JSON.parse(await read(root, 'vercel.json'));
  assert.ok(!vercelJson.crons, 'crons should be gone');
  assert.ok(vercelJson.functions, 'unrelated keys should survive');

  const manifest = JSON.parse(await read(root, 'infra/porter-schedules.json'));
  assert.equal(manifest.jobs.length, 2);
  assert.deepEqual(manifest.jobs.map((j: { schedule: string }) => j.schedule), ['0 9 * * *', '*/15 * * * *']);
  for (const job of manifest.jobs) {
    assert.match(job.url, /^\$\{PUBLIC_BASE_URL\}\/api\/cron\//);
    assert.equal(job.headers.authorization, 'Bearer ${CRON_SECRET}');
  }
  assert.match(await read(root, 'infra/scheduler.mjs'), /startScheduler/);
});

test('generated env example covers every variable the shims read', async (t) => {
  const root = await fixtureCopy();
  t.after(() => rm(dirname(root), { recursive: true, force: true }));
  await portRepo(root, { writeArtifacts: false });

  const env = await read(root, '.env.porter.example');
  for (const name of [
    'REDIS_URL',
    'S3_ENDPOINT',
    'S3_BUCKET',
    'S3_ACCESS_KEY_ID',
    'S3_SECRET_ACCESS_KEY',
    'BLOB_PUBLIC_BASE_URL',
    'BLOB_UPLOAD_SECRET',
    'CRON_SECRET',
    'PUBLIC_BASE_URL',
    'PORTER_EDGE_CONFIG_JSON',
  ]) {
    assert.ok(new RegExp(`^${name}=`, 'm').test(env), `${name} should be documented`);
  }
});

test('adapts to a src/ layout with no path alias', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'porter-src-'));
  t.after(() => rm(dir, { recursive: true, force: true }));

  await mkdir(join(dir, 'src/app'), { recursive: true });
  await writeFile(join(dir, 'package.json'), JSON.stringify({ name: 'a', dependencies: { next: '15.1.0', '@vercel/kv': '^3' } }), 'utf8');
  await writeFile(join(dir, 'next.config.mjs'), 'export default {};', 'utf8');
  await writeFile(join(dir, 'tsconfig.json'), JSON.stringify({ compilerOptions: { strict: true } }), 'utf8');
  await writeFile(join(dir, 'src/app/page.tsx'), "import { kv } from '@vercel/kv';\nexport default function P() { return null }\n", 'utf8');

  await portRepo(dir, { writeArtifacts: false });

  // Shims land under src/, and without an alias the import must be relative.
  assert.match(await read(dir, 'src/lib/porter/kv/index.ts'), /^\/\/ Generated by Porter/);
  assert.match(await read(dir, 'src/app/page.tsx'), /from '\.\.\/lib\/porter\/kv'/);
});

test('leaves a computed next.config alone and says so', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'porter-computed-'));
  t.after(() => rm(dir, { recursive: true, force: true }));

  await mkdir(join(dir, 'app'), { recursive: true });
  await writeFile(join(dir, 'package.json'), JSON.stringify({ name: 'a', dependencies: { next: '15.1.0' } }), 'utf8');
  await writeFile(join(dir, 'next.config.mjs'), 'const build = () => ({});\nexport default build();\n', 'utf8');
  await writeFile(join(dir, 'app/page.tsx'), 'export const revalidate = 60;\nexport default function P() { return null }\n', 'utf8');

  const { plan } = await portRepo(dir, { writeArtifacts: false });
  const isr = plan.steps.find((s) => s.id === 'isr');

  assert.ok(isr, 'the ISR step should still run');
  assert.equal(await read(dir, 'next.config.mjs'), 'const build = () => ({});\nexport default build();\n');
  assert.ok(isr!.caveats.some((c) => /[Cc]ould not wire/.test(c)), 'should warn that it could not wire the handler');
  // It could not fix it, so it must not claim it.
  assert.ok(plan.unhandled.some((f) => f.kind === 'isr'), 'the unfixed ISR finding should be reported');
});
